/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cy_libapkpatch_PatchUtils */

#ifndef _Included_com_cy_libapkpatch_PatchUtils
#define _Included_com_cy_libapkpatch_PatchUtils
#ifdef __cplusplus
extern "C" {
#endif


/*
 * Class:     viin_patch_update_PatchUpdate
 * Method:    patch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_cy_libapkpatch_PatchUtils_patch
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
